### PR TITLE
chore(moblie): bump to expo@52

### PR DESCRIPTION
**Pull request by dribble-njr**
## Checklist

- [ ] I have run `npx prisma migrate <name>` to generate migration files for schema changes.
- [ ] I have committed the generated migration files.

If you forget, the CI will block your pull request. Please fix it!

### CODE REVIEW

**Review by 4may-mcx — APPROVED** [review]

**Comment by dribble-njr** [comment]
[[SDK52] React-navigation stack navigation unmounts previous screen too early](https://github.com/expo/expo/issues/32425)

[When I want to go to the previous page, everything suddenly disappears](https://github.com/software-mansion/react-native-screens/issues/1685)

[Stack navigation unmounts previous screen too early with new arch](https://github.com/software-mansion/react-native-screens/issues/2459)

[When I want to go to the previous page, everything suddenly disappears](https://github.com/software-mansion/react-native-screens/issues/1685)

**Comment by dribble-njr** [comment]
好像这次 PR [Fix handling removal of transitioning views](https://github.com/facebook/react-native/pull/47634) 解决了。

**Comment by dribble-njr** [comment]
> 好像这次 PR [Fix handling removal of transitioning views](https://github.com/facebook/react-native/pull/47634) 解决了。

https://github.com/software-mansion/react-native-screens/pull/2596

**Comment by dribble-njr** [comment]
> > 好像这次 PR [Fix handling removal of transitioning views](https://github.com/facebook/react-native/pull/47634) 解决了。
> 
> [software-mansion/react-native-screens#2596](https://github.com/software-mansion/react-native-screens/pull/2596)

rn 需要升级到 0.77.0，等待发布

**Pull request merged**
